### ISSUE TITLE
Current Alpha Version Dashboard Can't Deploy Services

### ISSUE THREAD

**Issue by K123AsJ0k1** [oakestra/dashboard#47] opened 2024-02-03 15:44 UTC
# Bug Description

Oakestra dashboard setup with the command

```
sudo -E docker compose -f run-a-cluster/1-DOC.yaml -f run-a-cluster/override-alpha-versions.yaml up
```
isn't able to deploy services like the Oakestra repository README example Ngnix service, preventing user from deploying services in a similar way as with the dashboard stable version setup with the command
```
sudo -E docker compose -f run-a-cluster/1-DOC.yaml up
```
# Computer Resources

OS: Ubuntu 22.04.3 LTS 64-bit
CPU: Intel® Core™ i5-8250U CPU @ 1.60GHz × 8
Memory: 16.0 GiB
GPU: Mesa Intel® UHD Graphics 620 (KBL GT2)

# Reproduction Steps

1. Have a Ubuntu-22.04 laptop given by University of Helsinki with properly configured Docker engine or Docker desktop (True extent of custom configuration unknown)
2. Proceed with the setup as normal, but use the mentioned Alpha version command
3. Check that api/clusters and api/clusters/active show active node
4. Create an application with namespace test and name test
5. Create a Nginx service with a description similar to the one shown in the Oakestra repository README (lines 137-149):
```
Service name: nginx
Namespace: test
Virtualization: Container
Memory: 100MB
Vcpus: 1
Vgpus: 0
Vtpus: 0
Bandwidth in/out: 0
Storage: 0
Port: 6080:80
Code: docker.io/library/nginx:latest
```
7. Try to deploy the Nginx service

# Expected Behaviour

After deploying service, the service should be scheduled as normal as in the stable version.

# Actual Behaviour

After waiting, nothing happens regardless how many times user tries to deploy service, leaving the service say that no instances have been deployed.

![Oakestra_Alpha_Service_Deploy_1](https://github.com/oakestra/dashboard/assets/62049223/0eecc95b-228d-4fc5-a78a-f68bac3dc14d)

# Logs

[Oakestra nodeengine logs 1](https://github.com/oakestra/dashboard/files/14152017/Oakestra_Nodeengine_Logs_1.txt)
[Oakestra netmanager logs 1](https://github.com/oakestra/dashboard/files/14152018/Oakestra_Netmanager_Logs_1.txt)
[Oakestra alpha logs 1](https://github.com/oakestra/dashboard/files/14152019/Oakestra_Alpha_Logs_1.txt)

# Update

If I want to deploy a services using the Alpha version Dashboard, I can do it with the following actions:

```
export CLUSTER_NAME=example # No effect
export CLUSTER_LOCATION=48.26280440430051,11.66904127701312,2000 # No effect
export SYSTEM_MANAGER_URL=(device public IP) # Easiest to check in laptops using IP checker tool or ifconfig

sudo -E docker compose -f run-a-cluster/1-DOC.yaml -f run-a-cluster/override-alpha-versions.yaml up # Wait until HTTP requests are seen. If logs start to hang, CTRL + C and run the command again as many times it takes, usually 2-3 tries
Create another terminal and run sudo nano /etc/netmanager/netcfg.json # Set NodePublicAddress and ClusterUrl to be device public IP
sudo NetManager -p 6000
Create another terminal and run sudo NodeEngine -n 6000 -p 10100 -a (device public ip)
Open a dashboard and /api/docs in a browser
CTRL + C # After setup

sudo -E docker compose -f run-a-cluster/1-DOC.yaml up # Wait until HTTP requests are seen.  If logs start to hang, CTRL + C and run the command again as many times it takes, usually 2 tries
Use the same browser to view the dashboard in http://(device public ip)
Check if /api/clusters and /api/clusters/active in http:(device public ip):10000/api/docs show active nodes to be 1

Create application with test name and test namespace
Create a ngnix service as seen in Oakestra README, but change the port to 6080:80
Check if ngnix works by going to http://(device public ip):6080
```

![Oakestra_Alpha_Service_Deploy_2](https://github.com/oakestra/dashboard/assets/62049223/9f6eb78c-c454-4cbf-a439-d98c9f887812)

![Oakestra_Alpha_Service_Deploy_3](https://github.com/oakestra/dashboard/assets/62049223/8dc047c7-0066-478f-8590-1618a3ee22c3)

Unfortunately logs cannot be seen in service details using this method: 

![Oakestra_Alpha_Service_Deploy_4](https://github.com/oakestra/dashboard/assets/62049223/d7f829b9-fb93-45bd-b206-f834ea5cf542)

Additionally,  the dashboard might change back to the stable dashboard, when either device is restarted or applications are removed and browser restarted or changed:

![Oakestra_Alpha_Service_Deploy_5](https://github.com/oakestra/dashboard/assets/62049223/b9d77ad6-6b8c-4271-89ba-a684edc41cf3)

![Oakestra_Alpha_Service_Deploy_6](https://github.com/oakestra/dashboard/assets/62049223/21562bc4-8bee-4436-9565-ed30025537ab)

In the last picture I recreated application and Nginx service after opening the dashboard in Mozilla Firefox. I think this implies that the Alpha version is somehow cached into the browser, which it utilizes, when the change to Stable version happens.

**Comment by nitindermohan** [comment] 2024-02-05 01:19
@K123AsJ0k1 Thanks for opening the issue. Can you edit your description with the following information:

Step 1) The hardware configuration of the laptop? You can run `sudo lshw` to get your CPU, memory and GPU info.
Step 5) Please explicitly mention the service deployed. You can refer to the Oakestra README line numbers to be exact.

Thanks!

- NM

**Comment by K123AsJ0k1** [comment] 2024-02-05 16:22
Description is now updated with the wanted details. I wonder if the fact that the cached Alpha version is able to act like the stable version would prove that the problem is somewhere else.

**Comment by giobart** [comment] 2024-02-12 10:17
Hello just to clarify, is this bug happening only when creating the service using the form? Or does it happen while using an SLA file as well? E.g., does it work with this SLA? 

```
{
      "microservices" : [
        {
          "microserviceID": "",
          "microservice_name": "nginx",
          "microservice_namespace": "test",
          "virtualization": "container",
          "cmd": [],
          "memory": 100,
          "vcpus": 1,
          "vgpus": 0,
          "vtpus": 0,
          "bandwidth_in": 0,
          "bandwidth_out": 0,
          "storage": 0,
          "code": "docker.io/library/nginx:latest",
          "state": "",
          "port": "80",
          "addresses": {},
          "added_files": []
        }
      ]
}
```

**Comment by K123AsJ0k1** [comment] 2024-02-14 15:04
@giobart The bug also happens with SLA, so no services can be deployed.

**Comment by giobart** [comment] 2024-03-07 17:27
@K123AsJ0k1 This bug was caused by the resource abstractor on oakestra and is now solved. Closing this issue now:)

**Closed by giobart** 2024-03-07 17:27 UTC
Labels: bug, question
